# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/sergiudm"

[social.params]
icon = "brand-github"

[[social]]
identifier = "openreview"
name = "OpenReview"
url = "https://openreview.net/profile?id=~Qijun_Han2"

# [social.params]
# icon = "brand-openreview"
